<?php

//Tipične države v angleški ligi
$drzave = array(
    "DZ"=>"Alžirija",
    "EN"=>"Anglija",
    "AR"=>"Argentina",
    "BE"=>"Belgija",
    "BR"=>"Brazilija",
    "BF"=>"Burkina Faso",
    "CZ"=>"Češka",
    "DK"=>"Danska",
    "EG"=>"Egipt",
    "FI"=>"Finska",
    "FR"=>"Francija",
    "GH"=>"Gana",
    "GR"=>"Grčija",
    "GN"=>"Gvineja",
    "HR"=>"Hrvaška",
    "IE"=>"Irska",
    "IT"=>"Italija",
    "JM"=>"Jamajka",
    "JP"=>"Japonska",
    "KR"=>"Južna Koreja",
    "CM"=>"Kameron",
    "CO"=>"Kolumbija",
    "MA"=>"Maroko",
    "MX"=>"Mehika",
    "DE"=>"Nemčija",
    "NG"=>"Nigerija",
    "NL"=>"Nizozemska",
    "NO"=>"Norveška",
    "PL"=>"Polska",
    "PT"=>"Portugalska",
    "SN"=>"Senegal",
    "NIE"=>"Severna Irska",
    "CI"=>"Slonokoščena obala",
    "RS"=>"Srbija",
    "SC"=>"Škotska",
    "ES"=>"Španija",
    "SE"=>"Švedska",
    "CH"=>"Švica",
    "TH"=>"Tajska",
    "TN"=>"Tunizija",
    "TR"=>"Turčija",
    "UA"=>"Ukrajina",
    "UY"=>"Urugvaj",
    "WA"=>"Wales",
    "ZM"=>"Zambija",
    "US"=>"ZDA",
    "ZW"=>"Zimbabve"
);
?>